Menu
OrdinaryMack/Portfolio-Contact-form pull request #4
Opened 2023-10-25 16:33 UTC by OrdinaryMack

In this pull request -
1. Installed the linters for html,Css and JavaScript
2. Added the menu bar feature
3. Added the click active for the menu
4. Added the click action for the nav list tag
5. Stick to the design of figma

2023-10-26 15:31 UTC, HtetWaiYan7191 requested changes
# Hello TEAM  😁  , 

![](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)


Good job so far! 👍 💯 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights

Nice Design :heavy_check_mark: 
Correct Git Flow :heavy_check_mark: 
Descriptive Pr :heavy_check_mark: 
Mobile Menu is Working 💯 ✔️ 

## Required Changes ♻️


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-26 15:31 UTC, HtetWaiYan7191 commented on style.css
> +    left: 0;
[Optional] Instead of adding right: 0, you can set the width to 100% for your .mainMenu. Additionally, please consider using min-width for the mobile version, rather than max-width.

2023-10-26 15:31 UTC, HtetWaiYan7191 commented on style.css
> +    opacity: 0.9;
Kindly consider blurring the background content using backdrop-filter: blur(5px) or another approach. In the Figma design, when the mobile menu bar is open, the background content turns into a blur effect. 💯

2023-10-26 15:34 UTC, HtetWaiYan7191 commented on style.css
> +    opacity: 0.9;
I also noticed that this is a pair programming exercise. Please include commits from every member for the pair programming exercise. Currently, I have only seen two people's commits for this project. If you have other commitments, please let me know. 😁

2023-10-26 15:51 UTC, soesandarwin2201 approved these changes
Hi @OrdinaryMack , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Linters passed ✔️ 
- Good commit messages ✔️ 
- Good animation ✔️ 
- Clean code ✔️ 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
- Use more semantic tags
- Try to format the styles

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-10-28 02:55 UTC, HtetWaiYan7191 commented
# Congratulations 🎆 🚀 

Thank you for the extra effort you guys put into this pull request, even though it has already been approved. I apologize for the confusion. It appears that Ma Soe Sandar Win and I were reviewing your code simultaneously. Since Ma Soe Sandar Win has approved your code, you can now merge the pull request. Congratulations! 🥳🥳 @OrdinaryMack @Newt27 @mioOleen

2023-10-28 07:25 UTC, merged